// <auto-generated />
using System;
using Cobryx.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Cobryx.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(CobryxDbContext))]
    [Migration("20260212230000_FixSQLiteCompatibility")]
    partial class FixSQLiteCompatibility
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            // Designer file content is typically a full model snapshot, 
            // but for simple manual migrations acting as 'patches', 
            // the runtime only strictly needs the Migration class for Up/Down.
#pragma warning restore 612, 618
        }
    }
}
